# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Latitude')),
            ],
        ),
    ]
