# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 07:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DislikedShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True, verbose_name='Google ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shop name')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('address', models.CharField(max_length=255, verbose_name='Shop Address')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('favoris_of', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Favoris of'), default=[], size=None)),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop Icon')),
            ],
        ),
        migrations.AddField(
            model_name='dislikedshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', verbose_name='Shop'),
        ),
    ]
