# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
    ]
